from __future__ import annotations

import base64
import os
from dataclasses import dataclass
from html.parser import HTMLParser
from pathlib import Path
from typing import Iterable, TypedDict, cast

import requests
import base64
import re

from .config import Config


_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent"


@dataclass
class ImageSlot:
    src: str
    alt: str


class _ImgParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.slots: list[ImageSlot] = []

    def handle_starttag(self, tag: str, attrs: Iterable[tuple[str, str | None]]) -> None:
        if tag != "img":
            return
        attr_dict = dict(attrs)
        src = attr_dict.get("src")
        if not src or not src.startswith("assets/"):
            return
        alt = (attr_dict.get("alt") or "").strip()
        self.slots.append(ImageSlot(src=src, alt=alt))


def _discover_image_slots(index_path: Path) -> list[ImageSlot]:
    parser = _ImgParser()
    parser.feed(index_path.read_text(encoding="utf-8"))

    seen: set[str] = set()
    unique: list[ImageSlot] = []
    for slot in parser.slots:
        if slot.src in seen:
            continue
        seen.add(slot.src)
        unique.append(slot)
    return unique


_ASSET_PATTERN = re.compile(r"assets/[A-Za-z0-9._/-]+")


def _discover_asset_paths(site_dir: Path) -> set[str]:
    """Find all asset file references (HTML, CSS, JS) under the site dir."""
    assets: set[str] = set()
    for name in ("index.html", "styles.css", "main.js"):
        path = site_dir / name
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8", errors="ignore")
        assets.update(_ASSET_PATTERN.findall(text))
    return assets


_PLACEHOLDER_JPEG = base64.b64decode(
    """
    /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAARCAOEBkADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDyOijFGK7CQooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigAooxRigBaKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAFooopiCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACilooEJRS0FACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFABRS0UwEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKAEopaKACilooEFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAC0UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAC0UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFACUUtFABRRRQIKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAWiiimAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAtFFFAgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACilopgJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAJRS0UAFFLRQISilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooASilooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACilopgFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUALRRRTEFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH//2Q==
    """.replace("\n", "")
)
_PLACEHOLDER_PNG = base64.b64decode(
    """
    iVBORw0KGgoAAAANSUhEUgAABLAAAAK8CAIAAABwUdHZAAAQY0lEQVR4nO3d0a3YRhAEwT1jQlAQisn5B6IcbIAPQldFwN/GHLjv1+9/72/zfvoD/gPf/A3f/A3f/A3f/A3f/A3f/A3f/A3f/A3f/I1/fvoDAAAA+BmCEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIja33k+EQAAgP/LQggAABAlCAEAAKLmxSgAAECThRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAEDU/GQUAACgyUIIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbvnDiEAAECRhRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu3OYHgAAoMhCCAAAECUIAQAAoubFKAAAQJOFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQNT8ZBQAAKDJQggAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu+cOIQAAQJGFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG7c5geAACgyEIIAAAQJQgBAACi5sUoAABAk4UQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABA1PxkFAAAoMlCCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG75w4hAABAkYUQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbtzmB4AAKDIQggAABAlCAEAAKLmxSgAAECThRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAEDU/GQUAACgyUIIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbvnDiEAAECRhRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu3OYHgAAoMhCCAAAECUIAQAAoubFKAAAQJOFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQNT8ZBQAAKDJQggAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu+cOIQAAQJGFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG7c5geAACgyEIIAAAQJQgBAACi5sUoAABAk4UQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABA1PxkFAAAoMlCCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG75w4hAABAkYUQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbtzmB4AAKDIQggAABAlCAEAAKLmxSgAAECThRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAEDU/GQUAACgyUIIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbvnDiEAAECRhRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu3OYHgAAoMhCCAAAECUIAQAAoubFKAAAQJOFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQNT8ZBQAAKDJQggAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu+cOIQAAQJGFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG7c5geAACgyEIIAAAQJQgBAACi5sUoAABAk4UQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABA1PxkFAAAoMlCCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG75w4hAABAkYUQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbtzmB4AAKDIQggAABAlCAEAAKLmxSgAAECThRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAEDU/GQUAACgyUIIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbvnDiEAAECRhRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu3OYHgAAoMhCCAAAECUIAQAAoubFKAAAQJOFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQNT8ZBQAAKDJQggAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu+cOIQAAQJGFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG7c5geAACgyEIIAAAQJQgBAACi5sUoAABAk4UQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABA1PxkFAAAoMlCCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG75w4hAABAkYUQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbtzmB4AAKDIQggAABAlCAEAAKLmxSgAAECThRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAEDU/GQUAACgyUIIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbvnDiEAAECRhRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu3OYHgAAoMhCCAAAECUIAQAAoubFKAAAQJOFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQNT8ZBQAAKDJQggAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRu+cOIQAAQJGFEAAAIEoQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG7c5geAACgyEIIAAAQJQgBAACi5sUoAABAk4UQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIcpgcAAIiyEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABA1PxkFAAAoMlCCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAECUIAQAAIgShAAAAFG75w4hAABAkYUQAAAgShACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbtzmB4AAKDIQggAABAlCAEAAKLmxSgAAECThRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAohymBwAAiLIQAgAARAlCAACAKEEIAAAQJQgBAACiBCEAAEDU/GQUAACgyUIIAAAQJQgBAACiHKYHAACIshACAABECUIAAIAoQQgAABAlCAEAAKIEIQAAQJQgBAAAiBKEAAAAUbvnDiEAAECRhRAAACBKEAIAAEQJQgAAgChBCAAAECUIAQAAogQhAABAlCAEAACIEoQAAABRfwA2bAeZDHUV+wAAAABJRU5ErkJggg==
    """.replace("\n", "")
)


def _image_prompt(slot: ImageSlot, product_prompt: str) -> str:
    context = (product_prompt or "").strip()
    name_hint = Path(slot.src).stem.replace("-", " ").replace("_", " ")
    detail = slot.alt or f"{name_hint} for the product landing page"
    prompt_parts = [
        detail,
        "Photorealistic image, no text overlays, keep backgrounds clean.",
    ]
    if context:
        prompt_parts.append(f"Product context: {context}")
    if "hero" in slot.src.lower():
        prompt_parts.append("Wide 16:9 composition suitable for a hero banner.")
    else:
        prompt_parts.append("Cohesive color palette to match the page styling.")
    return " ".join(prompt_parts)


def _fallback_image_prompt(slot: ImageSlot, product_prompt: str, image_follow_up_context: str | None = None) -> str:
    prompt_parts = [_image_prompt(slot, product_prompt)]
    if image_follow_up_context:
        prompt_parts.append(f"User preferences: {image_follow_up_context}")
    return " ".join(prompt_parts)


class _PartPayload(TypedDict):
    text: str


class _ContentPayload(TypedDict):
    role: str
    parts: list[_PartPayload]


class _GenerationConfig(TypedDict):
    responseModalities: list[str]


class _UsageMetadata(TypedDict, total=False):
    promptTokenCount: int
    candidatesTokenCount: int
    totalTokenCount: int


class _InlineData(TypedDict):
    data: str


class _PartResponse(TypedDict, total=False):
    inlineData: _InlineData
    inline_data: _InlineData


class _ContentResponse(TypedDict):
    parts: list[_PartResponse]


class _CandidateResponse(TypedDict):
    content: _ContentResponse


class _GenerateContentResponse(TypedDict, total=False):
    candidates: list[_CandidateResponse]
    usageMetadata: _UsageMetadata


def _request_image(prompt: str, model: str, api_key: str) -> tuple[bytes, _UsageMetadata | None]:
    # Use responseModalities for the Gemini 3 image models (responseMimeType is rejected with
    # INVALID_ARGUMENT on those preview endpoints).
    generation_config: _GenerationConfig = {"responseModalities": ["IMAGE"]}

    contents: list[_ContentPayload] = [{"role": "user", "parts": [{"text": prompt}]}]
    payload: dict[str, object] = {"contents": contents, "generationConfig": generation_config}

    resp = requests.post(
        _API_URL.format(model=model),
        params={"key": api_key},
        json=payload,
        timeout=120,
    )
    if resp.status_code != 200:
        raise RuntimeError(f"Gemini image request failed: {resp.status_code} {resp.text}")

    data = cast(_GenerateContentResponse, resp.json())
    try:
        candidates = data.get("candidates")
        if not candidates:
            raise KeyError("candidates")
        part = candidates[0]["content"]["parts"][0]
        inline = part.get("inlineData") or part.get("inline_data")
        if not inline:
            raise KeyError("inlineData")
        image_b64 = inline["data"]
    except (KeyError, IndexError) as exc:
        raise RuntimeError(f"Unexpected Gemini image response: {data}") from exc

    usage = data.get("usageMetadata")
    return base64.b64decode(image_b64), usage


def ensure_placeholder_assets(slug: str, project_root: Path) -> list[Path]:
    """Create lightweight placeholder files for any referenced assets that don't exist."""
    site_dir = project_root / "sites" / slug
    if not site_dir.exists():
        raise FileNotFoundError(f"Site directory not found: {site_dir}")

    assets = _discover_asset_paths(site_dir)
    created: list[Path] = []
    for rel_path in assets:
        path = site_dir / rel_path
        if path.exists():
            try:
                # Gemini sometimes leaves zero-byte placeholder files; treat them as missing.
                if path.stat().st_size > 0:
                    continue
            except OSError:
                # If we cannot stat the file, fall back to recreating it as a placeholder.
                pass
        path.parent.mkdir(parents=True, exist_ok=True)
        ext = path.suffix.lower()
        if ext in {".jpg", ".jpeg"}:
            data = _PLACEHOLDER_JPEG
        else:
            data = _PLACEHOLDER_PNG
        path.write_bytes(data)
        created.append(path)
    return created


def generate_images_for_site(
    slug: str,
    product_prompt: str,
    project_root: Path,
    config: Config,
    overwrite: bool = False,
    image_follow_up_context: str | None = None,
    debug: bool = False,
) -> list[Path]:
    api_key = config.gemini_api_key or os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("Set GEMINI_API_KEY to enable Gemini image generation.")

    site_dir = project_root / "sites" / slug
    index_path = site_dir / "index.html"
    if not index_path.exists():
        raise FileNotFoundError(f"Site directory not found: {site_dir}")

    slots = _discover_image_slots(index_path)
    if not slots:
        return []

    generated: list[Path] = []
    for slot in slots:
        target_path = site_dir / slot.src
        if target_path.exists() and not overwrite:
            continue

        from . import gemini_runner  # Local import to avoid circular dependency.

        prompt_text = None
        try:
            prompt_text = gemini_runner.generate_image_prompt(
                slot_src=slot.src,
                slot_alt=slot.alt,
                product_prompt=product_prompt,
                project_root=project_root,
                config=config,
                follow_up_context=image_follow_up_context,
                debug=debug,
            )
        except Exception as exc:
            print(f"[Gemini Images] Falling back to default prompt for {slot.src}: {exc}")

        prompt_text = prompt_text or _fallback_image_prompt(
            slot, product_prompt, image_follow_up_context=image_follow_up_context
        )
        image_bytes, usage = _request_image(prompt_text, config.gemini_image_model, api_key)

        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_bytes(image_bytes)
        if usage:
            prompt_tokens = usage.get("promptTokenCount")
            completion_tokens = usage.get("candidatesTokenCount")
            total_tokens = usage.get("totalTokenCount")

            message = (
                f"[Gemini Images] Tokens used (model={config.gemini_image_model}): "
                f"prompt={prompt_tokens}, completion={completion_tokens}, total={total_tokens}"
            )

            total = total_tokens
            if total is None and (prompt_tokens is not None or completion_tokens is not None):
                total = (prompt_tokens or 0) + (completion_tokens or 0)

            if config.gemini_image_cost_per_1k_tokens is not None and total is not None:
                estimated_cost = (total / 1000.0) * config.gemini_image_cost_per_1k_tokens
                message += f", estimated_cost={estimated_cost:.6f} USD"

            print(message)
        generated.append(target_path)

    return generated
